rgw: bl make GetBL response s3cmd compatibile
when target_prefix isn't specified, s3 would still return TargetPrefix
attributes.previous impl will cause s3cmd parse error as following:

s3cmd accesslog  -c user.s3cfg  s3://user --debug

DEBUG: Response: {'status': 200, 'headers': {'date': 'Mon, 24 Apr 2017
09:03:01 GMT', 'content-length': '195', 'x-amz-request-id':
'tx000000000000000000007-0058fdbf45-1009-default', 'content-type':
'application/xml'}, 'reason': 'OK', 'data': '<?xml version="1.0"
encoding="UTF-8"?><BucketLoggingStatus
xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LoggingEnabled><TargetBucket>user</TargetBucket></LoggingEnabled></BucketLoggingStatus>'}
DEBUG: ConnMan.put(): connection put back to
pool (http://localhost:8000#1) Access logging for: s3://user/ Logging
Enabled: True

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising '/usr/bin/s3cmd' using UTF-8
DEBUG: Unicodising 'accesslog' using UTF-8
DEBUG: Unicodising '-c' using UTF-8
DEBUG: Unicodising 'user.s3cfg' using UTF-8
DEBUG: Unicodising 's3://user' using UTF-8
DEBUG: Unicodising '--debug' using UTF-8
Invoked as: /usr/bin/s3cmd accesslog -c user.s3cfg s3://user --debug
Problem: AttributeError: 'NoneType' object has no attribute 'text'
S3cmd:   1.6.1
python:   2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 2000, in cmd_accesslog
    output(u"     Target prefix: %s" % accesslog.targetPrefix().uri())
  File "/usr/lib/python2.7/site-packages/S3/AccessLog.py", line 50, in targetPrefix
    self.tree.find(".//LoggingEnabled//TargetPrefix").text)
AttributeError: 'NoneType' object has no attribute 'text'

Signed-off-by: Jiaying Ren <jiaying.ren@umcloud.com>